spring:
  application:
    name: eureka-server
server:
  port: 8002
eureka:
  instance:
    hostname: node2
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://node1:8001/eureka,http://node3:8003/eureka